@api_url = http://localhost:5000

### API Info
GET {{api_url}}/api

### Health check
GET {{api_url}}/health

### Get all team members
# @name getAllTeamMembers
GET {{api_url}}/api/team-members
Content-Type: application/json

### Get backend team members
GET {{api_url}}/api/role/backend/error

### Get frontend team members
GET {{api_url}}/api/role/frontend

### Get team member by id
@team_member_id = 6efe9d3b-4d7c-47b1-8bdb-d870617f8ae6
GET {{api_url}}/api/team-members/{{team_member_id}}

### Create team member
# @name createTeamMember
POST {{api_url}}/api/team-members HTTP/1.1
Content-Type: application/json

{
    "name": "Eveline",
    "role": "1",
    "grade": "10"
}

### Update team member
PUT {{api_url}}/api/team-members HTTP/1.1
Content-Type: application/json

{
    "id": "33eb9a1c-33f0-4533-954a-2e880d06f8c0",
    "name": "Jonass",
    "role": "JavaScript",
    "grade": "9"
}

### Delete team member
DELETE {{api_url}}/api/team-members/cea26791-948f-4b2d-99a3-328eb6941f81 HTTP/1.1