@api_url = http://localhost:5000

### API Info
GET {{api_url}}/api

### Health check
GET {{api_url}}/health

### Get all team members
# @name getAllTeamMembers
GET {{api_url}}/api/team-members
Content-Type: application/json

### Get team member by id
@team_member_id = 37eabf45-8736-49c4-90e1-af2a7d5653cc
GET {{api_url}}/api/team-members/{{team_member_id}}

### Create team member
# @name createTeamMember
POST {{api_url}}/api/team-members HTTP/1.1
Content-Type: application/json

{
    "name": "Bartek",
    "role": "DevOps",
    "grade": "7"
}

### Update team member
PUT {{api_url}}/api/team-members HTTP/1.1
Content-Type: application/json

{
    "id": "8ce7c22b-5fcc-49fb-9bb2-fe7db6f263d1",
    "name": "Jonass",
    "role": "JavaScript",
    "grade": "9"
}

### Delete team member
DELETE {{api_url}}/api/team-members/8ce7c22b-5fcc-49fb-9bb2-fe7db6f263d1 HTTP/1.1